// Generated by https://github.com/zhyupe/ffxiv-opcode-worker

namespace Sapphire.Common.Packets
{
    enum ServerZoneIpcTypeCN : ushort
    {
        ActorCast = 0x00A5,
        ActorControl = 0x0312,
        ActorControlSelf = 0x02B0,
        ActorControlTarget = 0x02C6,
        ActorFreeSpawn = 0x036E,
        ActorGauge = 0x02F2,
        ActorMove = 0x02DC,
        ActorSetPos = 0x00F8,
        AddStatusEffect = 0x037C,
        AoeEffect16 = 0x0300,
        AoeEffect24 = 0x024A,
        AoeEffect32 = 0x027B,
        AoeEffect8 = 0x01A8,
        CFNotify = 0x0301,
        Chat = 0x00bb,
        ContainerInfo = 0x0234,
        CurrencyCrystalInfo = 0x00CA,
        DirectorStart = 0x0307,
        Effect = 0x03D2,
        EventFinish = 0x00A4,
        EventPlay = 0x0176,
        EventPlay4 = 0x0118,
        EventStart = 0x014C,
        Examine = 0x0094,
        ExamineSearchInfo = 0x00B3,
        GroupMessage = 0x0065,
        InitZone = 0x0294,
        InventoryActionAck = 0x019F,
        InventoryTransaction = 0x038F,
        InventoryTransactionFinish = 0x03CE,
        ItemInfo = 0x00CF,
        MarketBoardItemListing = 0x02A4,
        MarketBoardItemListingCount = 0x01D1,
        MarketBoardItemListingHistory = 0x0187,
        MarketBoardSearchResult = 0x01EB,
        MarketTaxRates = 0x0069,
        NpcSpawn = 0x01D3,
        ObjectSpawn = 0x01BA,
        PlaceFieldMarker = 0x0319,
        PlaceFieldMarkerPreset = 0x0068,
        PlayerSetup = 0x02f5,
        PlayerSpawn = 0x00B5,
        PlayerStats = 0x0186,
        Playtime = 0x0217,
        PrepareZoning = 0x00F6,
        RetainerInformation = 0x01B4,
        SomeDirectorUnk4 = 0x02D2,
        StatusEffectList = 0x0360,
        UpdateClassInfo = 0x02C3,
        UpdateHpMpTp = 0x00D8,
        UpdateInventorySlot = 0x0165,
        UpdateSearchInfo = 0x010E,
    };

    enum ClientZoneIpcTypeCN : ushort
    {
        ChatHandler = 0x0267,
        ClientTrigger = 0x0141,
        InventoryModifyHandler = 0x0127,
        SetSearchInfoHandler = 0x01AB,
        UpdatePositionHandler = 0x00CC,
        UpdatePositionInstance = 0x0181,
    };

    enum ServerChatIpcTypeCN : ushort
    {

    };

    enum ClientChatIpcTypeCN : ushort
    {

    };
}
