name: Build and push to node-machina-ffxiv

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Setup Nuget.exe
      uses: NuGet/setup-nuget@v1.0.5
    - name: Install dependencies
      run: nuget restore
    - name: Build DotNet4
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\MachinaWrapper.sln /t:Build /p:Configuration=Release
    - name: Check for duplicate opcodes
      run: ./MachinaWrapper/bin/Release/MachinaWrapper.exe --Test
    - name: Clone node-machina-ffxiv
      run: git clone https://github.com/karashiiro/node-machina-ffxiv.git
    - name: Move build results into node-machina-ffxiv
      run: |
        del ./node-machina-ffxiv/MachinaWrapper/*.dll
        del ./node-machina-ffxiv/MachinaWrapper/*.exe
        del ./node-machina-ffxiv/MachinaWrapper/*.config
        move ./MachinaWrapper/bin/Release/*.dll, ./MachinaWrapper/bin/Release/*.exe, ./MachinaWrapper/bin/Release/*.config ./node-machina-ffxiv/MachinaWrapper
    - name: Configure GitHub user
      run: |
        cd node-machina-ffxiv
        git config --global user.email "action@github.com"
        git config --global user.name "Push To node-machina"
        git config credential.helper store
        git commit -a -m "Import new build results from MachinaWrapperJSON"
    - name: Push build results to node-machina-ffxiv
      uses: ad-m/github-push-action@master
      with:
        directory: ./node-machina-ffxiv
        repository: karashiiro/node-machina-ffxiv
        github_token: ${{ secrets.WORKER_ACCESS_KEY }}
